basePath: /
definitions:
  service.DexPairInfo:
    properties:
      dex_slug:
        type: string
      last_updated:
        type: string
      liquidity:
        type: number
      name:
        type: string
      network_slug:
        type: string
      percent_change_price_1h:
        type: number
      price:
        type: number
    type: object
  service.NFTFloorPriceInfo:
    properties:
      collection_slug:
        type: string
      floor_price:
        type: number
      floor_price_symbol:
        type: string
      floor_price_usd:
        type: number
    type: object
  utils.TokenInfo:
    properties:
      lastUpdated:
        type: string
      percentChange1h:
        format: float64
        type: number
      percentChange24h:
        format: float64
        type: number
      price:
        format: float64
        type: number
      symbol:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a crypto monitoring server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Crypto Monitoring API
  version: "1.0"
paths:
  /api/v1/dex/pair:
    get:
      consumes:
      - application/json
      description: Get information about DEX pairs (supports comma-separated addresses)
      parameters:
      - description: Contract Addresses (comma-separated)
        in: query
        name: contract_address
        required: true
        type: string
      - description: Network Slug
        in: query
        name: network_slug
        type: string
      - description: Network ID
        in: query
        name: network_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.DexPairInfo'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Dex Pair Info
      tags:
      - dex
  /api/v1/nft/floor_price:
    get:
      consumes:
      - application/json
      description: Get floor price of NFT collections
      parameters:
      - description: Collection Slugs (comma separated)
        in: query
        name: slugs
        type: string
      - description: Convert to USD
        in: query
        name: convert_to_usd
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.NFTFloorPriceInfo'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get NFT Floor Price
      tags:
      - nft
  /api/v1/token/price:
    get:
      consumes:
      - application/json
      description: Get price of tokens by IDs
      parameters:
      - description: Token IDs (comma separated)
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/utils.TokenInfo'
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Token Price
      tags:
      - token
  /ping:
    get:
      consumes:
      - application/json
      description: Check server health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping
      tags:
      - health
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
